### PR TITLE
Add documentation for SCLOrkWiimote

### PR DESCRIPTION
**Pull request by lnihlen**

### CODE REVIEW

**Comment by lnihlen** [comment]
SCLOrkTools release 0.0.14 contains documentation for SCLOrkWiimote. Please let me know if you have any more issues using the software, or if the documentation leaves questions unanswered.

Cheers!

**Comment by grammoboy2** [comment]
I'm pretty new to SC, but when using the updater in Quarks.gui; SC 3.11, there is no update for SCLOrk

**Comment by lnihlen** [comment]
0.0.14 is the release that contains the updated documentation, what version are you seeing there?

**Comment by grammoboy2** [comment]
0.0.13

**Comment by lnihlen** [comment]
Did you hit "check for updates" button in the upper-left hand corner of the Quarks gui?

**Comment by lnihlen** [comment]
oh - I noticed, you've forked my fork of SCLOrkTools for some reason

**Comment by lnihlen** [comment]
oh no that's somebody else n/m

**Comment by grammoboy2** [comment]
yes
>
> Did you hit "check for updates" button in the upper-left hand corner 
> of the Quarks gui?
>

**Comment by lnihlen** [comment]
idk what to tell ya - working on my end. Can you post a screenshot of the SCLOrkTools quark metadata from Quarks.gui?

**Comment by grammoboy2** [comment]
0.0.14 is listed. I would expect it would update automatically.

**Comment by brunoruviaro** [comment]
Also have you tried the non-gui method?

Quarks.update("SCLOrkTools");

(tell us what gets posted after running this in SC)

...and most importantly, recompile class library after running the line
above (control + shift + enter)

Bruno

**Comment by grammoboy2** [comment]
On 4/19/20 12:12 AM, Bruno Ruviaro wrote:
> Also have you tried the non-gui method?
>
> Quarks.update("SCLOrkTools");
>
> (tell us what gets posted after running this in SC)


SCLOrkTools installed
Quark 'SCLOrkTools' updated to version: 0.0.13 tag: nil refspec: 
decbdf0dff86f5a2c0b3ec4e9c4b2d32a76a65e2

**Comment by grammoboy2** [comment]
On 4/19/20 12:15 AM, rosea.grammostola wrote:
>
> On 4/19/20 12:12 AM, Bruno Ruviaro wrote:
>> Also have you tried the non-gui method?
>>
>> Quarks.update("SCLOrkTools");
>>
>> (tell us what gets posted after running this in SC)
>
>
> SCLOrkTools installed
> Quark 'SCLOrkTools' updated to version: 0.0.13 tag: nil refspec: 
> decbdf0dff86f5a2c0b3ec4e9c4b2d32a76a65e2

Now:


Quark 'SCLOrkTools' updated to version: 0.0.14 tag: tags/0.0.14 refspec: 
tags/0.0.14
-> Quarks

**Comment by grammoboy2** [comment]
Ok seems to work now. Documentation is there. Thanks again for your hard 
work!
> Now:
>
>
> Quark 'SCLOrkTools' updated to version: 0.0.14 tag: tags/0.0.14 
> refspec: tags/0.0.14
> -> Quarks

**Comment by lnihlen** [comment]
Happy Wiimoting!

**Comment by lnihlen** [comment]
(as an aside) - I've been doing lightweight git tags for releasing, wondering if doing annotated tags would work better. Will try that next time.

**Comment by grammoboy2** [comment]
(
SCLOrkWiimote.isConnected;
)

(
~w = SCLOrkWiimote.new;
)



HID: found 2 devices
IdentityDictionary[ (1 -> a HIDInfo(, Nintendo RVL-CNT-01, IDs:1406, 
774, /dev/hidraw1, 00:27:09:26:19:91, 0, -1)) ]
-> true
HID: found 2 devices
IdentityDictionary[ (1 -> a HIDInfo(, Nintendo RVL-CNT-01, IDs:1406, 
774, /dev/hidraw1, 00:27:09:26:19:91, 0, -1)) ]
ERROR: Message 'productID' not understood.
RECEIVER:
    nil
ARGS:
PATH: /home/user/supercollider/Wii-hid-1.scd
CALL STACK:
     DoesNotUnderstandError:reportError
         arg this = <instance of DoesNotUnderstandError>
     Nil:handleError
         arg this = nil
         arg error = <instance of DoesNotUnderstandError>
     Thread:handleError
         arg this = <instance of Thread>
         arg error = <instance of DoesNotUnderstandError>
     Object:throw
         arg this = <instance of DoesNotUnderstandError>
     Object:doesNotUnderstand
         arg this = nil
         arg selector = 'productID'
         arg args = [*0]
     Meta_SCLOrkWiimote:new
         arg this = <instance of Meta_SCLOrkWiimote>
         var deviceList = <instance of IdentityDictionary>
         var productId = nil
         var path = nil
         var hid = nil
     < closed FunctionDef >  (no arguments or variables)
     Interpreter:interpretPrintCmdLine
         arg this = <instance of Interpreter>
         var res = nil
         var func = <instance of Function>
         var code = "(
~w = SCLOrkWiimote.new;
)"
         var doc = nil
         var ideClass = <instance of Meta_ScIDE>
     Process:interpretPrintCmdLine
         arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'productID' not 
understood.
RECEIVER: nil

**Comment by lnihlen** [comment]
If this is a bug report, can you please file a bug report, instead of just posting a log dump on an old PR? And can you please include some descriptive text, an explanation of your setup, any other things you think might be useful and save me my valuable free time while fixing your problem, and maybe a polite request for a stranger to offer you free technical support on the internet?

**Comment by lnihlen** [comment]
Also, at minimum, please note that the documentation states that multiple Wiimotes are not currently supported.

**Pull request merged**
